# Generated by Django 3.1.4 on 2021-06-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_key',
            field=models.CharField(default='c8c5265a47', max_length=10, unique=True),
        ),
    ]
