# Generated by Django 2.2.10 on 2021-06-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupman',
            name='password',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='pickupman',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
