# Generated by Django 2.2.10 on 2021-06-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210612_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=''),
        ),
        migrations.AddField(
            model_name='transaction',
            name='time',
            field=models.DateField(default=''),
        ),
    ]
